$(function(){
    $('.web_box_9').click(function(){
        $('.web_popup_list_9').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_9').removeClass('web_pop');
    })
     $('.web_box_10').click(function(){
        $('.web_popup_list_10').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_10').removeClass('web_pop');
    })
     $('.web_box_11').click(function(){
        $('.web_popup_list_11').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_11').removeClass('web_pop');
    })
     $('.web_box_12').click(function(){
        $('.web_popup_list_12').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_12').removeClass('web_pop');
    })
     $('.event_box_1').click(function(){
        $('.event_popup_list_1').addClass('pop');
    })
     $('.close').click(function(){
         $('.event_popup_list_1').removeClass('pop');
    })
     $('.event_box_2').click(function(){
        $('.event_popup_list_2').addClass('pop');
    })
     $('.close').click(function(){
         $('.event_popup_list_2').removeClass('pop');
    })
     $('.event_box_3').click(function(){
        $('.event_popup_list_3').addClass('pop');
    })
     $('.close').click(function(){
         $('.event_popup_list_3').removeClass('pop');
    })
     $('.event_box_4').click(function(){
        $('.event_popup_list_4').addClass('pop');
    })
     $('.close').click(function(){
         $('.event_popup_list_4').removeClass('pop');
    })
     
});