$(function(){
    $('.web_box_1').click(function(){
        $('.web_popup_list_1').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_1').removeClass('web_pop');
    })
     $('.web_box_2').click(function(){
        $('.web_popup_list_2').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_2').removeClass('web_pop');
    })
     $('.web_box_3').click(function(){
        $('.web_popup_list_3').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_3').removeClass('web_pop');
    })
     $('.web_box_4').click(function(){
        $('.web_popup_list_4').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_4').removeClass('web_pop');
    })
     $('.web_box_5').click(function(){
        $('.web_popup_list_5').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_5').removeClass('web_pop');
    })
     $('.web_box_6').click(function(){
        $('.web_popup_list_6').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_6').removeClass('web_pop');
    })
     $('.web_box_7').click(function(){
        $('.web_popup_list_7').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_7').removeClass('web_pop');
    })
     $('.web_box_8').click(function(){
        $('.web_popup_list_8').addClass('web_pop');
    })
     $('.close').click(function(){
         $('.web_popup_list_8').removeClass('web_pop');
    })

});